analysis/urls.py
from django.urls import path
from .views import *

app_name = 'analysis'

urlpatterns = [
    path('index/', analysis_index, name='index'),
    path('', analysis_create, name='create'),
    path('detail/<int:id>', analysis_detail, name='detail'),
    path('index/detail/<int:id>', analysis_detail, name='detail2'),
]

umay/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis.urls')),
    path('', home_view, name='home'),
    path('favicon.ico', favicon_view),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analysis/models.py
from django.db import models
from django.urls import reverse


class Analysis(models.Model):
	file = models.FileField(null=False, blank=False)

	def get_absolute_url(self):
		return reverse('analysis:detail', kwargs={'id': self.id})

	def get_create_url(self):
#		return reverse('analysis:create')
		return reverse('home')

	def get_from_results(self):
		return reverse('analysis:detail2', kwargs={'id': self.id})



	class Meta:
		ordering = ['-id']

home/models.py
from django.db import models

# Create your models here.

analysis/forms.py
from django import forms
from .models import Analysis

class AnalysisForm(forms.ModelForm):

	class Meta:
		model = Analysis
		fields = [
			'file',
		]

analysis/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect
from .models import Analysis
from .forms import AnalysisForm
from django.contrib import messages
from django.utils.text import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
import subprocess, os


def analysis_index(request):
    file_list = Analysis.objects.all()

    query = request.GET.get('q')
    if query:
        file_list = file_list.filter(file__icontains=query)

    paginator = Paginator(file_list, 20)  # Show 20 uploads per page

    page = request.GET.get('page')
    try:
        uploads = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        uploads = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        uploads = paginator.page(paginator.num_pages)

    return render(request, 'analysis/index.html', {'uploads': uploads})


def analysis_detail(request, id):
    analyzed = get_object_or_404(Analysis, id=id)
    url = request.get_full_path()
    if url.find("index") == 1:
        result_file_path = os.path.join(settings.BASE_DIR, 'results', analyzed.file.name)
        with open(result_file_path, "r") as f:
            results = f.read()
    else:
        results = subprocess_script(analyzed.file.url)
        result_file_path = os.path.join(settings.BASE_DIR, 'results', analyzed.file.name)
        with open(result_file_path, "w") as f:
            f.write(results)

    if results[:-1] == "exit":
        context = {
            'analyzed': analyzed,
            'failed': 'failed',
        }
    elif results[:-1] == "[]":
        context = {
            'analyzed': analyzed,
            'empty': 'empty',
        }


    else:
        results = results[2:-3].split("}, {")
        query = request.GET.get('q')
        if query:
            results = [k for k in results if query in k]

        res = []
        for i in results:
            i = "{" + i + "}"
            i2 = eval(i)
            res.append(i2)
        results = res

        context = {
            'analyzed': analyzed,
            'results': results,
        }

    return render(request, 'analysis/detail.html', context)


def analysis_create(request):
    form = AnalysisForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        analysis = form.save()
        return HttpResponseRedirect(analysis.get_absolute_url())

    context = {
        'form': form,
    }
    return render(request, 'home.html', context)


def subprocess_script( file_from_form ):
    sample_path = settings.BASE_DIR / file_from_form[1:]
    try:
        output = subprocess.run([settings.BASE_DIR / 'analysis.py', sample_path], capture_output=True, text=True)
        stdout = output.stdout
    except Exception as e:
        stdout = "exit\n"
    return stdout

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home_view(request):
	context = {
		'name': 'test'
	}

	return render(request, 'home.html', context)

templates/analysis/detail.html
{% extends 'base.html' %}
{% block title %} Detail - {{ block.super }} {% endblock %}
{% block body %}

	<div class="conatainer-fluid">
		<div class="row">
			<div class="col-md-6 offset-lg-2">

				{% if results %}
					<div class="alert alert-success" role="alert">
					  <h4 class="alert-heading">Success!</h4>
					  <p>The table below shows samples that have shared code with <b>"{{ analyzed.file.name }}"</b>.</p>
					</div>
					<table class="table table-hover table-bordered">
					  <thead class="thead-dark table-dark">

						<tr>
						  <th scope="col">Sample</th>
						  <th scope="col">Basic Blocks</th>
						  <th scope="col">Functions</th>
						</tr>
					  </thead>
					  <tbody>
						{% for result in results %}
							<tr>
							  <th scope="row"><a href="https://www.virustotal.com/gui/file/{{ result.File }}">{{ result.File }}</a></th>
							  <td>{{ result.BasicBlocks }}</td>
							  <td>{{ result.Functions }}</td>
							</tr>
						{% endfor %}
					  </tbody>
					</table>
				{% endif %}



				{% if failed %}
					<div class="alert alert-danger" role="alert">
					  <h4 class="alert-heading">Failed!</h4>
					  <p>The functions and basic blocks of the given file could not be extracted.</p>
					</div>
				{% endif %}


				{% if empty %}
					<div class="alert alert-warning" role="alert">
					  <h4 class="alert-heading">Shared code not found!</h4>
					</div>
				{% endif %}


			</div>
		</div>
	</div>

{% endblock %}

templates/analysis/index.html
{% extends 'base.html' %}
{% block title %} Index - {{ block.super }} {% endblock %}

{% block body %}

	<div class="conatainer">
		{% for u in uploads %}
		<div class="row">
			<div class="col-md-6 offset-md-1">
				<a href="{{ u.get_from_results }}">{{ u.file.name }}</a><br>
			</div>
		</div>

		{% endfor %}

		<div class="row">
			<div class="col-md-6 offset-md-1">
				<div class="pagination">
					<span class="step-links">
						{% if uploads.has_previous %}
							<a class="btn btn-primary btn-sm" href="?page={{ uploads.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" role="button">previous</a>
						{% endif %}

						<span class="current">
							<b>Page {{ uploads.number }} of {{ uploads.paginator.num_pages }}</b>
						</span>

						{% if uploads.has_next %}
							<a class="btn btn-primary btn-sm" href="?page={{ uploads.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" role="button">next</a>
						{% endif %}
					</span>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/base.html
{% load static %}

<html>
<head>
	<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Umay{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

	{% include 'header.html' %}

	{% include 'messages.html' %}

	{% block body %}

	{% endblock %}

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/header.html
{% load static %}
  <head>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color: #1c3793">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'img/logo.png' %}" width="80" height="40" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'analysis:index' %}"><b>Index</b></a>
            </li>
          </ul>
          
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <a class="nav-link" href="https://github.com/mucoze/Umay">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
              </svg>
            </a>                 
          </ul>

          <form class="d-flex">
            <input class="form-control me-2" type="search" name="q" placeholder="Search" value="{{ request.GET.q }}" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>

        </div>
      </div>
    </nav>

  </head>

templates/home.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} {% endblock %}

{% block body %}


	<div class="conatainer">
		<div class="row">
			<div class="col-md-6 offset-md-2">
				<form method='POST' enctype="multipart/form-data">
					{% csrf_token %}
					<h1>Upload the sample</h1>
					{{ form.as_p }}<br>
					<b><p>Once uploaded, the analysis starts automatically.</p></b>
					<input class="btn btn-success" type='submit' value='Upload', name='fname'>
					{{ form.name }}
					</form>
			</div>
		</div>
	</div>





{% endblock %}

templates/messages.html
{% if messages %}

    {% for message in messages %}

		<div class="alert alert-success alert-dismissible fade show" role="alert">
		  {{ message }}
		  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>

    {% endfor %}

{% endif %}